"""The text of docs/eda.md: one function per section, all reading the same `Results`.

Rules the text follows:

- A bullet in a numbered section states numbers and cites the figure or table that holds
  them. It states no direction; directions are left to the findings, which are checked.
- A section says at its top whether it is modeling-relevant (landmarks before 2018-01-01
  only, Section 10) or descriptive only.
"""

from collections.abc import Callable, Sequence
from typing import Any

from trialpulse.eda import analysis as an
from trialpulse.eda.charts import FIGURES
from trialpulse.eda.findings import findings
from trialpulse.eda.results import (
    AMENDMENT_LANDMARK_MONTHS,
    COVID_END,
    COVID_START,
    DESCRIPTIVE,
    PHASE_LABEL,
    STATE_MONTHS,
    STATE_TABLE_MONTHS,
    TABLE_MONTHS,
    Results,
    groups,
    row,
)
from trialpulse.reports import markdown_table

DISCLAIMER = "Research demo. Not medical advice. Not for patient decision-making."
MODELING = "modeling"
DESCRIPTIVE_ONLY = DESCRIPTIVE.capitalize()


def pct(value: float | None, digits: int = 1) -> str:
    return "n/a" if value is None else f"{100 * value:.{digits}f}%"


def num(value: Any) -> str:
    return "n/a" if value is None else f"{int(value):,}"


def dec(value: float | None, digits: int = 0) -> str:
    return "n/a" if value is None else f"{value:.{digits}f}"


def days(value: float) -> str:
    return f"{value:.0f} day" if round(value) == 1 else f"{value:.0f} days"


def _figure(number: int) -> list[str]:
    name, caption = FIGURES[number]
    return [f"![Figure {number}: {caption}](figures/{name})", "", f"*Figure {number}. {caption}.*"]


def _cif_table(
    rows: an.Rows,
    first: str,
    months: Sequence[int],
    label: Callable[[dict[str, Any]], str] = lambda r: str(r["group"]),
    cif: str = "CIF at {m} months",
) -> list[str]:
    headers = [first, "Trials", "Early stops by the cutoff", *[cif.format(m=m) for m in months]]
    body = [
        [label(r), num(r["trials"]), num(r["early_stops"]), *[pct(r[f"cif_{m}m"]) for m in months]]
        for r in rows
    ]
    return markdown_table(headers, body)


def _use(r: dict[str, Any]) -> str:
    return DESCRIPTIVE if r["descriptive"] else MODELING


def _modeling_tag(res: Results) -> str:
    return f"*Modeling-relevant: landmarks before {res.before.isoformat()} only.*"


def _header(res: Results) -> list[str]:
    cutoff, before = res.cutoff.isoformat(), res.before.isoformat()
    return [
        "# Exploratory data analysis",
        "",
        DISCLAIMER,
        "",
        "This file is generated by `uv run python -m trialpulse.eda.report` (CLAUDE.md Step 5). "
        "Do not edit it by hand: change `src/trialpulse/eda/` and regenerate.",
        "",
        "- **Source:** ClinicalTrials.gov registry records, through the version-history dataset "
        f"`brbk/clinical_trials_history` (license CC-BY-NC-4.0): {res.stamp}.",
        f"- **Data as of {cutoff}**, the latest post date in the pinned dataset revision. "
        "TrialPulse normalizes the records and derives the cohort, the outcomes and every "
        "statistic shown here.",
        f"- **Cohort:** {num(res.landmark_rows)} landmark rows of {num(res.landmark_trials)} "
        "trials (`data/cohort/landmarks.parquet`, built in Step 4).",
        "",
        "## How to read this report",
        "",
        '- **What is measured.** An "early stop" is a trial\'s first TERMINATED or WITHDRAWN '
        "version, and completion is the competing event (CLAUDE.md Section 6). Probabilities "
        "are cumulative incidence functions (CIF) from the Aalen-Johansen estimator: a trial "
        "still open at the data cutoff counts for as long as it was followed, and a completed "
        "trial can no longer stop early.",
        f"- **Modeling-relevant** sections use landmarks before {before} only (Section 10), "
        "because later landmarks belong to the locked test origins. Their outcomes are "
        "followed to the data cutoff.",
        f"- **{DESCRIPTIVE_ONLY}** sections and rows look at later dates, or at fields that "
        "are not point-in-time. They are labeled, and nothing in them is used to choose "
        "features or models.",
        "- **Phase** has no version history (ADR 0006), so the phase section uses the "
        "current-record phase and is descriptive only, not used for modeling.",
        "- **Every statement cites the figure or table that holds its numbers.** The findings "
        "in the last section are checked against the numbers each time the report is "
        "regenerated, and the command refuses to write a finding the data no longer supports.",
        '- This describes registry records. "Elevated early-stop risk" is an operational '
        "statement about a trial record, never a statement about whether a treatment works.",
        "- **No confidence intervals.** This report describes. Each table shows the size of "
        "its groups, and comparisons with bootstrap intervals come with the models in Steps 9 "
        "to 11.",
    ]


def _risk_after_registration(res: Results) -> list[str]:
    short, long_, far = res.short, res.long, TABLE_MONTHS[-1]
    cs, cl = f"cif_{short}m", f"cif_{long_}m"
    everyone = row(res.sponsor, "group", an.ALL)
    industry, other = row(res.sponsor, "group", "INDUSTRY"), row(res.sponsor, "group", "OTHER")
    by_year = groups(res.year)
    top = max(by_year, key=lambda r: r[cs])
    first, last = res.by_landmark[0], res.by_landmark[-1]
    return [
        "## 1. Early-stop risk after registration",
        "",
        _modeling_tag(res),
        f"{num(everyone['trials'])} trials that were open at registration (landmark index 0), "
        f"first posted from {res.first_year}-01-01 to {res.last_modeling_day.isoformat()} and "
        f"followed to {res.cutoff.isoformat()}.",
        "",
        *_figure(1),
        "",
        "Table 1. Early-stop CIF by lead sponsor class at registration. OTHER is the registry's "
        "class for universities, hospitals and other organizations; the remaining classes "
        "(FED, OTHER_GOV, NETWORK, INDIV, UNKNOWN and records without a class) are pooled.",
        "",
        *_cif_table(res.sponsor, "Sponsor class", TABLE_MONTHS),
        "",
        f"- {pct(everyone[cs])} of trials stopped early within {short} months of registration "
        f"and {pct(everyone[cl])} within {long_} months (Table 1).",
        f"- INDUSTRY trials are at {pct(industry[cs])} after {short} months and "
        f"{pct(industry[f'cif_{far}m'])} after {far}; OTHER trials are at {pct(other[cs])} and "
        f"{pct(other[f'cif_{far}m'])} (Figure 1, Table 1).",
        "",
        *_figure(2),
        "",
        "Table 2. Early-stop CIF by year of registration.",
        "",
        *_cif_table(res.year, "Registration year", res.horizons),
        "",
        f"- From {by_year[0]['group']} to {by_year[-1]['group']} the {long_}-month CIF lies "
        f"between {pct(min(r[cl] for r in by_year))} and {pct(max(r[cl] for r in by_year))}; "
        f"the highest {short}-month CIF is {pct(top[cs])}, for trials registered in "
        f"{top['group']} (Figure 2, Table 2).",
        "",
        "Table 3. Early-stop CIF over the months after each landmark, for trials still open at "
        "that landmark.",
        "",
        *_cif_table(
            res.by_landmark,
            "Months since registration",
            res.horizons,
            lambda r: f"{r['group'] * res.spacing_months} (landmark index {r['group']})",
            "CIF within {m} months of the landmark",
        ),
        "",
        f"- A trial still open at a landmark has a {short}-month CIF of {pct(first[cs])} at "
        f"registration and {pct(last[cs])} {last['group'] * res.spacing_months} months later "
        "(Table 3).",
    ]


def _phase(res: Results) -> list[str]:
    cl = f"cif_{res.long}m"
    phases = [r for r in res.phase if r["group"] in an.PHASE_ORDER]
    low, high = min(phases, key=lambda r: r[cl]), max(phases, key=lambda r: r[cl])
    lines = [
        "## 2. Phase (descriptive only, not used for modeling)",
        "",
        f"*{PHASE_LABEL}.* Phase has no version history in the dataset (ADR 0006), so this "
        "section uses each trial's current-record phase from the API v2 snapshot of "
        f"{res.snapshot}. A phase edited after a trial's outcome was known would leak that "
        "outcome, so these numbers are not used to choose features or models. The trials are "
        "the same as in section 1.",
        "",
        *_figure(3),
        "",
        f"Table 4. {PHASE_LABEL}: early-stop CIF by current-record phase group.",
        "",
        *_cif_table(res.phase, "Phase group (current record)", res.horizons),
        "",
        f"- {DESCRIPTIVE_ONLY}: across phase groups the {res.long}-month CIF runs from "
        f'{pct(low[cl])} for "{low["group"]}" to {pct(high[cl])} for "{high["group"]}" '
        "(Figure 3, Table 4).",
    ]
    missing = [r for r in res.phase if r["group"] == an.NO_CURRENT_RECORD]
    if missing:
        lines.append(
            f"- {DESCRIPTIVE_ONLY}: {num(missing[0]['trials'])} trials have no record in the "
            "snapshot and form their own row (Table 4)."
        )
    return lines


def _competing(res: Results) -> list[str]:
    end, short, long_ = STATE_MONTHS, res.short, res.long
    columns = ("terminated", "withdrawn", "early_stop", "completed", "open", "naive_early_stop")
    headers = ["Months since registration", "Terminated", "Withdrawn", "Early stop (both)",
               "Completed", "Still open", "Early stop, completion as censoring"]  # fmt: skip
    body = [[m, *[pct(res.state(key, m)) for key in columns]] for m in STATE_TABLE_MONTHS]
    return [
        "## 3. Stopping competes with completing",
        "",
        _modeling_tag(res) + " The trials are the same as in section 1.",
        "",
        *_figure(4),
        "",
        *_figure(5),
        "",
        "Table 5. Share of trials in each state by months since registration (Aalen-Johansen), "
        "and the early-stop estimate that treats a completion as censoring (1 minus "
        "Kaplan-Meier).",
        "",
        *markdown_table(headers, body),
        "",
        f"- {end} months after registration {pct(res.state('completed', end))} of trials have "
        f"completed, {pct(res.state('early_stop', end))} have stopped early and "
        f"{pct(res.state('open', end))} are still open (Figure 4, Table 5).",
        f"- By {short} months {pct(res.state('withdrawn', short))} of trials are withdrawn and "
        f"{pct(res.state('terminated', short))} terminated; by {end} months, "
        f"{pct(res.state('withdrawn', end))} and {pct(res.state('terminated', end))} (Table 5).",
        f"- Treating completion as censoring gives {pct(res.state('naive_early_stop', long_))} "
        f"at {long_} months and {pct(res.state('naive_early_stop', end))} at {end} months, "
        f"against {pct(res.state('early_stop', long_))} and {pct(res.state('early_stop', end))} "
        "from the competing-risks estimator (Figure 5, Table 5).",
    ]


def _amendments(res: Results) -> list[str]:
    at, long_ = AMENDMENT_LANDMARK_MONTHS, res.long
    outcomes = res.amendments_outcome
    stopped, completed = outcomes[0], outcomes[1]
    by_outcome = [[label, *[pct(r[key]) for r in outcomes]] for key, label in an.SIGNALS]
    by_outcome.append(
        ["Median versions posted so far", *[dec(r["median_versions"]) for r in outcomes]]
    )
    by_outcome.append(
        [
            "Median months moved, where the primary completion date moved later",
            *[dec(r["median_slip_months"]) for r in outcomes],
        ]
    )
    cif_headers = ["Signal at the landmark", "Trials with", "Trials without", "Not known",
                   f"CIF at {long_} months with", f"CIF at {long_} months without",
                   "Ratio"]  # fmt: skip
    cif_body = [
        [r["signal"], num(r["with"]), num(r["without"]), num(r["unknown"]), pct(r["cif_with"]),
         pct(r["cif_without"]), dec(r["ratio"], 2)]
        for r in res.amendments_cif
    ]  # fmt: skip
    lines = [
        f"## 4. Amendments by the {at}-month landmark",
        "",
        _modeling_tag(res),
        f"{num(res.amendment_rows)} trials still open {at} months after registration (landmark "
        f"index {at // res.spacing_months}). Each signal compares the record as it stood at the "
        "landmark, from versions posted on or before it, with the trial's first version. "
        "Nothing posted after the landmark is read. Dates are compared by calendar month.",
        "",
        f"Table 6. Share of trials showing each signal at the {at}-month landmark, by what "
        "happened to the trial afterwards.",
        "",
        *markdown_table(
            ["Signal at the landmark", *[f"{r['group']} ({num(r['trials'])})" for r in outcomes]],
            by_outcome,
        ),
        "",
        f"- {pct(stopped['primary_completion_later'])} of the trials that later stopped early "
        "had moved their primary completion date later by the landmark, and "
        f"{pct(completed['primary_completion_later'])} of the trials that later completed "
        "(Table 6).",
        f"- {pct(stopped['not_yet_recruiting'])} of the trials that later stopped early were "
        f"still not yet recruiting, against {pct(completed['not_yet_recruiting'])} of those "
        f"that later completed; {pct(stopped['ever_suspended'])} against "
        f"{pct(completed['ever_suspended'])} had been suspended (Table 6).",
        "",
        *_figure(6),
        "",
        f"Table 7. Early-stop CIF in the {long_} months after the {at}-month landmark, with and "
        f"without each signal. Over all {num(res.amendment_rows)} trials it is "
        f"{pct(res.amendment_overall)}. A signal is not known when one of its inputs is missing.",
        "",
        *markdown_table(cif_headers, cif_body),
        "",
    ]
    signal = {r["key"]: r for r in res.amendments_cif}
    for key, text in (
        ("ever_suspended", "with a suspension on record"),
        ("not_yet_recruiting", "for trials still not yet recruiting"),
        ("primary_completion_later", "where the primary completion date moved later"),
        ("enrollment_cut", "where the enrollment target was cut by 10% or more"),
    ):
        if key in signal:
            lines.append(
                f"- The {long_}-month CIF is {pct(signal[key]['cif_with'])} {text} and "
                f"{pct(signal[key]['cif_without'])} otherwise (Figure 6, Table 7)."
            )
    return lines


def _registration_lag(res: Results) -> list[str]:
    cl = f"cif_{res.long}m"
    years = res.registration_years
    first, last = years[0], [r for r in years if not r["descriptive"]][-1]
    timing = {r["group"]: r for r in res.timing}
    headers = ["Registration year", "Use", "Trials", "Registered after the start",
               "Median days late, among those", "More than 1 year late",
               "Median days from submission to first posting"]  # fmt: skip
    body = [
        [r["year"], _use(r), num(r["trials"]), pct(r["share_after_start"]),
         dec(r["median_days_late"]), pct(r["share_over_a_year_late"]),
         dec(r["median_days_submit_to_post"])]
        for r in years
    ]  # fmt: skip
    return [
        "## 5. Registration lag",
        "",
        f"*Years before {res.before.year} are modeling-relevant; rows from {res.before.year} on "
        f"are {DESCRIPTIVE} and marked.* Trials open at registration (landmark index 0). A "
        "trial is registered after its start when the whole period of its first version's "
        "start date lies before the first-post date.",
        "",
        *_figure(7),
        "",
        "Table 8. Registration timing by year of registration. The last year runs to "
        f"{res.cutoff.isoformat()}.",
        "",
        *markdown_table(headers, body),
        "",
        f"- {pct(first['share_after_start'])} of the trials registered in {first['year']} were "
        f"registered after their start date, with a median delay of "
        f"{dec(first['median_days_late'])} days; in {last['year']} it was "
        f"{pct(last['share_after_start'])} and {dec(last['median_days_late'])} days (Figure 7, "
        "Table 8).",
        "",
        "Table 9. Early-stop CIF by registration timing. Modeling-relevant: landmarks before "
        f"{res.before.isoformat()} only.",
        "",
        *_cif_table(res.timing, "Registration timing", TABLE_MONTHS),
        "",
        f"- The {res.long}-month CIF is {pct(timing[an.PROSPECTIVE][cl])} for trials registered "
        f"on or before their start date, {pct(timing[an.LATE_WITHIN_YEAR][cl])} for trials "
        f"registered up to 1 year after it and {pct(timing[an.LATE_OVER_YEAR][cl])} for trials "
        "registered more than 1 year after it (Table 9).",
    ]


def _post_dates(res: Results) -> list[str]:
    rows = res.post_dates
    headers = ["Year of posting", "Use", "Versions", "ESTIMATED post date",
               "Median days from submission to posting", "90th percentile"]  # fmt: skip
    body = [
        [r["year"], _use(r), num(r["versions"]), pct(r["share_estimated"]),
         dec(r["median_days_to_post"]), dec(r["p90_days_to_post"])]
        for r in rows
    ]  # fmt: skip
    lines = [
        "## 6. Estimated post dates",
        "",
        f"*A property of the registry's records, not of outcomes; rows from {res.before.year} "
        f"on are still marked {DESCRIPTIVE}.* The version clock is each version's post date "
        "(Section 6). A post date marked ESTIMATED was derived by the registry and not "
        "recorded.",
        "",
        *_figure(8),
        "",
        "Table 10. Versions of cohort trials by year of posting: the share with an ESTIMATED "
        "post date, and the days from submission to posting.",
        "",
        *markdown_table(headers, body),
        "",
    ]
    full = [r for r in rows if r["share_estimated"] >= 0.999]
    partial = [r for r in rows if 0.001 < r["share_estimated"] < 0.999]
    none = [r for r in rows if r["share_estimated"] <= 0.001]
    if full and none:
        between = "".join(f", {pct(r['share_estimated'])} in {r['year']}" for r in partial)
        lines += [
            f"- The ESTIMATED share is {pct(full[-1]['share_estimated'])} in every year through "
            f"{full[-1]['year']}{between} and {pct(none[0]['share_estimated'])} from "
            f"{none[0]['year']} on (Figure 8, Table 10).",
            "- The median time from submission to posting is "
            f"{days(full[-1]['median_days_to_post'])} in {full[-1]['year']} and "
            f"{days(none[0]['median_days_to_post'])} in {none[0]['year']}; the 90th "
            f"percentile is {dec(full[-1]['p90_days_to_post'])} and "
            f"{dec(none[0]['p90_days_to_post'])} days (Table 10).",
        ]
    return lines


def _covid(res: Results) -> list[str]:
    peak_name, peak_rate, _ = res.covid_peak()
    baseline, shock = res.covid_summary[0], res.covid_summary[1]
    headers = ["Period", "Months", "Trials under follow-up (average)",
               *[f"{label} per 1,000" for _, label in an.COVID_SERIES]]  # fmt: skip
    body = [
        [r["period"], r["months"], num(r["open_trials"]),
         *[dec(r[f"{key}_per_1000"], 2) for key, _ in an.COVID_SERIES]]
        for r in res.covid_summary
    ]  # fmt: skip
    return [
        "## 7. The COVID period (descriptive only)",
        "",
        f"*{DESCRIPTIVE_ONLY}, not used for modeling.* Calendar months from "
        f"{COVID_START.isoformat()[:7]} to {COVID_END.isoformat()[:7]}, which include the "
        "locked test and stress-test years. A rate is the number of events posted in a month "
        "per 1,000 cohort trials under follow-up at the start of that month. A suspension is a "
        "SUSPENDED version that follows a version with another status.",
        "",
        *_figure(9),
        "",
        f"Table 11. {DESCRIPTIVE_ONLY}: average monthly rates per 1,000 trials under follow-up.",
        "",
        *markdown_table(headers, body),
        "",
        f"- {DESCRIPTIVE_ONLY}: new suspensions averaged {dec(baseline['suspended_per_1000'], 2)} "
        f"per 1,000 trials per month in {baseline['period']}, and the highest month is "
        f"{peak_name} with {dec(peak_rate, 1)} (Figure 9, Table 11).",
        f"- {DESCRIPTIVE_ONLY}: terminations averaged {dec(baseline['terminated_per_1000'], 2)} "
        f"per 1,000 in {baseline['period']} and {dec(shock['terminated_per_1000'], 2)} in "
        f"{shock['period']}; withdrawals {dec(baseline['withdrawn_per_1000'], 2)} and "
        f"{dec(shock['withdrawn_per_1000'], 2)} (Table 11).",
    ]


def _findings(res: Results) -> list[str]:
    lines = ["## 8. Findings and what they imply for modeling", ""]
    for number, finding in enumerate(findings(res), start=1):
        lines += [
            f"{number}. **{finding.title}.** {finding.evidence}",
            f"   *Implication for modeling:* {finding.implication}",
        ]
    return lines


def _not_here() -> list[str]:
    return [
        "## Not in this report",
        "",
        "- **Why trials stop.** The reasons section (distribution by year, phase and sponsor "
        "class) waits for the final Step 6 labels and will be added as an addendum.",
        "- **Therapeutic areas.** No point-in-time therapeutic area exists in the version "
        "history (ADR 0007), so there is no breakdown by area.",
        "- **Models.** Nothing here fits or evaluates a model, and no locked origin was evaluated.",
    ]


def render(res: Results) -> str:
    """The whole document. Raises StaleFindingError before returning anything if a finding
    is no longer supported."""
    sections = [
        _header(res),
        _risk_after_registration(res),
        _phase(res),
        _competing(res),
        _amendments(res),
        _registration_lag(res),
        _post_dates(res),
        _covid(res),
        _findings(res),
        _not_here(),
    ]
    return "\n\n".join("\n".join(section) for section in sections) + "\n"
