"""The text of docs/eda.md: one function per section, all reading the same `Results`.

Rules the text follows:

- A bullet in a numbered section states numbers and cites the figure or table that holds
  them. It states no direction; directions are left to the findings, which are checked.
- A section says at its top whether it is modeling-relevant (nothing dated 2018-01-01 or
  later is read, Section 10) or descriptive only.
- Figures and tables are cited by name through `refs`, which numbers them.
"""

from collections.abc import Callable, Sequence
from typing import Any

from trialpulse.eda import analysis as an
from trialpulse.eda.findings import findings
from trialpulse.eda.refs import FIGURES, cite, figure_number, table_number
from trialpulse.eda.results import (
    AMENDMENT_LANDMARK_MONTHS,
    COVID_END,
    COVID_START,
    DESCRIPTIVE,
    LAPSE_MONTHS,
    PHASE_LABEL,
    STATE_MONTHS,
    STATE_TABLE_MONTHS,
    TABLE_MONTHS,
    Results,
    followed,
    groups,
    row,
)
from trialpulse.reports import markdown_table

DISCLAIMER = "Research demo. Not medical advice. Not for patient decision-making."
MODELING = "modeling"
DESCRIPTIVE_ONLY = DESCRIPTIVE.capitalize()


def pct(value: float | None, digits: int = 1) -> str:
    return "n/a" if value is None else f"{100 * value:.{digits}f}%"


def num(value: Any) -> str:
    return "n/a" if value is None else f"{round(value):,}"


def dec(value: float | None, digits: int = 0) -> str:
    return "n/a" if value is None else f"{value:.{digits}f}"


def days(value: float) -> str:
    return f"{value:.0f} day" if round(value) == 1 else f"{value:.0f} days"


def _figure(key: str) -> list[str]:
    name, caption = FIGURES[key]
    number = figure_number(key)
    return [f"![Figure {number}: {caption}](figures/{name})", "", f"*Figure {number}. {caption}.*"]


def _table(key: str, caption: str) -> str:
    return f"Table {table_number(key)}. {caption}"


def _cif_table(
    rows: an.Rows,
    first: str,
    months: Sequence[int],
    label: Callable[[dict[str, Any]], str] = lambda r: str(r["group"]),
    cif: str = "CIF at {m} months",
) -> list[str]:
    headers = [first, "Trials", "Early stops observed", *[cif.format(m=m) for m in months]]
    body = [
        [label(r), num(r["trials"]), num(r["early_stops"]), *[pct(r[f"cif_{m}m"]) for m in months]]
        for r in rows
    ]
    return markdown_table(headers, body)


def _use(r: dict[str, Any]) -> str:
    return DESCRIPTIVE if r["descriptive"] else MODELING


def _modeling_tag(res: Results) -> str:
    return f"*Modeling-relevant: nothing dated {res.before.isoformat()} or later is read.*"


def _header(res: Results) -> list[str]:
    cutoff, before = res.cutoff.isoformat(), res.before.isoformat()
    return [
        "# Exploratory data analysis",
        "",
        DISCLAIMER,
        "",
        "This file is generated by `uv run python -m trialpulse.eda.report` (CLAUDE.md Step 5). "
        "Do not edit it by hand: change `src/trialpulse/eda/` and regenerate.",
        "",
        "- **Source:** ClinicalTrials.gov registry records, through the version-history dataset "
        f"`brbk/clinical_trials_history` (license CC-BY-NC-4.0): {res.stamp}.",
        f"- **Data as of {cutoff}**, the latest post date in the pinned dataset revision. "
        "TrialPulse normalizes the records and derives the cohort, the outcomes and every "
        "statistic shown here.",
        f"- **Cohort as of {before}:** {num(res.landmark_rows)} landmark rows of "
        f"{num(res.landmark_trials)} trials (`data/cohort/training/origin_{before}/`). The "
        "modeling-relevant sections read this cohort.",
        f"- **Final cohort:** {num(res.final_landmark_rows)} landmark rows of "
        f"{num(res.final_landmark_trials)} trials (`data/cohort/landmarks.parquet`), with "
        "outcomes through the data cutoff. Only the descriptive rows and sections read it.",
        "",
        "## How to read this report",
        "",
        '- **What is measured.** An "early stop" is a trial\'s first TERMINATED or WITHDRAWN '
        "version, and completion is the competing event (CLAUDE.md Section 6). Probabilities "
        "are cumulative incidence functions (CIF) from the Aalen-Johansen estimator: a trial "
        "whose follow-up ends without an outcome counts for as long as it was followed, and a "
        "completed trial can no longer stop early.",
        f"- **Modeling-relevant** sections read nothing dated {before} or later (Section 10). "
        f"They use the cohort as it would have been built on {before} (ADR 0016): only "
        "versions posted before that date are known, and observation ends there. A trial's "
        "outcome, its censoring under the UNKNOWN rule and its place in the cohort are what "
        "was known on that date, exactly as for a model trained at the 2018 origin "
        "(Section 6). The locked test years stay unseen.",
        f"- **{DESCRIPTIVE_ONLY}** sections and rows look at later dates, or at fields that "
        "are not point-in-time. They are labeled, and nothing in them is used to choose "
        "features or models.",
        "- **Phase** has no version history (ADR 0006), so the phase section uses the "
        "current-record phase and is descriptive only, not used for modeling.",
        "- **Censoring.** Follow-up ends without an outcome in two ways: at the end of the "
        f"observation window ({before} in modeling-relevant sections), or earlier under the "
        "registry's UNKNOWN rule, when a record passed its completion date and went 2 years "
        "without a status verification (ADR 0014). The estimator treats both as unrelated to "
        f"the outcome; Table {table_number('lapse')} shows how common the second kind is.",
        "- **Months and dates.** A horizon of m months is m times 365.25 / 12 days after the "
        "landmark (the evaluation harness of Step 8 counts calendar months, which differs only "
        "for an event that falls exactly on the horizon day). Dates are compared by calendar "
        "month, because the registry gives them to the month through 2016 and mostly to the "
        "day from 2017.",
        "- **Every statement cites the figure or table that holds its numbers.** The findings "
        "in the last section are checked against the numbers each time the report is "
        "regenerated, and the command refuses to write a finding the data no longer supports.",
        "- **No confidence intervals.** This report describes. Each table shows the size of "
        "its groups, and comparisons with bootstrap intervals come with the models in Steps 9 "
        "to 11.",
        '- This describes registry records. "Elevated early-stop risk" is an operational '
        "statement about a trial record, never a statement about whether a treatment works.",
    ]


def _risk_after_registration(res: Results) -> list[str]:
    short, long_, far = res.short, res.long, TABLE_MONTHS[-1]
    cs, cl, lapse = f"cif_{short}m", f"cif_{long_}m", f"lapse_{LAPSE_MONTHS[-1]}m"
    everyone = row(res.sponsor, "group", an.ALL)
    industry, other = row(res.sponsor, "group", "INDUSTRY"), row(res.sponsor, "group", "OTHER")
    industry_lapse, other_lapse = (row(res.lapse, "group", g) for g in ("INDUSTRY", "OTHER"))
    by_year = groups(res.year)
    short_years, long_years = followed(by_year, cs), followed(by_year, cl)
    top = max(short_years, key=lambda r: r[cs])
    first, last = res.by_landmark[0], res.by_landmark[-1]
    before = res.before.isoformat()
    lapse_headers = ["Sponsor class", "Trials", f"Censored under the UNKNOWN rule before {before}",
                     *[f"Incidence at {m} months" for m in LAPSE_MONTHS]]  # fmt: skip
    lapse_body = [
        [r["group"], num(r["trials"]), num(r["lapsed"]),
         *[pct(r[f"lapse_{m}m"]) for m in LAPSE_MONTHS]]
        for r in res.lapse
    ]  # fmt: skip
    return [
        "## 1. Early-stop risk after registration",
        "",
        _modeling_tag(res),
        f"{num(everyone['trials'])} trials that were open at registration (landmark index 0), "
        f"first posted from {res.first_year}-01-01 to {res.last_modeling_day.isoformat()}, with "
        f"outcomes observed before {before}.",
        "",
        *_figure("sponsor"),
        "",
        _table(
            "sponsor",
            "Early-stop CIF by lead sponsor class at registration. OTHER is the registry's class "
            "for universities, hospitals and other organizations; the remaining classes (FED, "
            "OTHER_GOV, NETWORK, INDIV, UNKNOWN and records without a class) are pooled.",
        ),
        "",
        *_cif_table(res.sponsor, "Sponsor class", TABLE_MONTHS),
        "",
        f"- {pct(everyone[cs])} of trials stopped early within {short} months of registration "
        f"and {pct(everyone[cl])} within {long_} months {cite(tables='sponsor')}.",
        f"- INDUSTRY trials are at {pct(industry[cs])} after {short} months and "
        f"{pct(industry[f'cif_{far}m'])} after {far}; OTHER trials are at {pct(other[cs])} and "
        f"{pct(other[f'cif_{far}m'])} {cite('sponsor', 'sponsor')}.",
        "",
        _table(
            "lapse",
            "Censoring under the UNKNOWN rule by sponsor class: trials whose follow-up ended "
            "that way, and its cumulative incidence with early stop and completion as "
            "competing events.",
        ),
        "",
        *markdown_table(lapse_headers, lapse_body),
        "",
        f"- Within {LAPSE_MONTHS[-1]} months of registration {pct(industry_lapse[lapse])} of "
        f"INDUSTRY trials and {pct(other_lapse[lapse])} of OTHER trials are censored under the "
        f"UNKNOWN rule {cite(tables='lapse')}.",
        "",
        *_figure("year"),
        "",
        _table(
            "year",
            "Early-stop CIF by year of registration. A cell is shown only where every trial of "
            f"the year could be followed for the whole horizon before {before}.",
        ),
        "",
        *_cif_table(res.year, "Registration year", res.horizons),
        "",
        f"- From {long_years[0]['group']} to {long_years[-1]['group']} the {long_}-month CIF "
        f"lies between {pct(min(r[cl] for r in long_years))} and "
        f"{pct(max(r[cl] for r in long_years))}; the highest {short}-month CIF is "
        f"{pct(top[cs])}, for trials registered in {top['group']} {cite('year', 'year')}.",
        "",
        _table(
            "landmark",
            "Early-stop CIF over the months after each landmark, for trials still open at that "
            "landmark.",
        ),
        "",
        *_cif_table(
            res.by_landmark,
            "Months since registration",
            res.horizons,
            lambda r: f"{r['group'] * res.spacing_months} (landmark index {r['group']})",
            "CIF within {m} months of the landmark",
        ),
        "",
        f"- A trial still open at a landmark has a {short}-month CIF of {pct(first[cs])} at "
        f"registration and {pct(last[cs])} {last['group'] * res.spacing_months} months later "
        f"{cite(tables='landmark')}.",
    ]


def _phase(res: Results) -> list[str]:
    cl = f"cif_{res.long}m"
    phases = [r for r in res.phase if r["group"] in an.PHASE_ORDER]
    low, high = min(phases, key=lambda r: r[cl]), max(phases, key=lambda r: r[cl])
    lines = [
        "## 2. Phase (descriptive only, not used for modeling)",
        "",
        f"*{PHASE_LABEL}.* Phase has no version history in the dataset (ADR 0006), so this "
        "section uses each trial's current-record phase from the API v2 snapshot of "
        f"{res.snapshot}. A phase edited after a trial's outcome was known would leak that "
        "outcome, so these numbers are not used to choose features or models. The trials and "
        "their outcomes are the same as in section 1.",
        "",
        *_figure("phase"),
        "",
        _table("phase", f"{PHASE_LABEL}: early-stop CIF by current-record phase group."),
        "",
        *_cif_table(res.phase, "Phase group (current record)", res.horizons),
        "",
        f"- {DESCRIPTIVE_ONLY}: across phase groups the {res.long}-month CIF runs from "
        f'{pct(low[cl])} for "{low["group"]}" to {pct(high[cl])} for "{high["group"]}" '
        f"{cite('phase', 'phase')}.",
    ]
    missing = [r for r in res.phase if r["group"] == an.NO_CURRENT_RECORD]
    if missing:
        lines.append(
            f"- {DESCRIPTIVE_ONLY}: {num(missing[0]['trials'])} trials have no record in the "
            f"snapshot and form their own row {cite(tables='phase')}."
        )
    return lines


def _competing(res: Results) -> list[str]:
    end, short, long_ = STATE_MONTHS, res.short, res.long
    columns = ("terminated", "withdrawn", "early_stop", "completed", "open", "naive_early_stop")
    headers = ["Months since registration", "Terminated", "Withdrawn", "Early stop (both)",
               "Withdrawn share of early stops", "Completed", "Still open",
               "Early stop, completion as censoring"]  # fmt: skip
    body = []
    for m in STATE_TABLE_MONTHS:
        cells = [pct(res.state(key, m)) for key in columns]
        body.append([m, *cells[:3], pct(res.withdrawn_share(m)), *cells[3:]])
    return [
        "## 3. Stopping competes with completing",
        "",
        _modeling_tag(res) + " The trials and their outcomes are the same as in section 1.",
        "",
        *_figure("states"),
        "",
        *_figure("naive"),
        "",
        _table(
            "states",
            "Share of trials in each state by months since registration (Aalen-Johansen), and "
            "the early-stop estimate that treats a completion as censoring (1 minus "
            "Kaplan-Meier).",
        ),
        "",
        *markdown_table(headers, body),
        "",
        f"- {end} months after registration {pct(res.state('completed', end))} of trials have "
        f"completed, {pct(res.state('early_stop', end))} have stopped early and "
        f"{pct(res.state('open', end))} are still open {cite('states', 'states')}.",
        f"- By {short} months {pct(res.state('withdrawn', short))} of trials are withdrawn and "
        f"{pct(res.state('terminated', short))} terminated; by {end} months, "
        f"{pct(res.state('withdrawn', end))} and {pct(res.state('terminated', end))} "
        f"{cite(tables='states')}.",
        f"- Treating completion as censoring gives {pct(res.state('naive_early_stop', long_))} "
        f"at {long_} months and {pct(res.state('naive_early_stop', end))} at {end} months, "
        f"against {pct(res.state('early_stop', long_))} and {pct(res.state('early_stop', end))} "
        f"from the competing-risks estimator {cite('naive', 'states')}.",
    ]


def _amendments(res: Results) -> list[str]:
    at, long_ = AMENDMENT_LANDMARK_MONTHS, res.long
    outcomes = res.amendments_outcome
    stopped, completed = outcomes[0], outcomes[1]
    by_outcome = [[label, *[pct(r[key]) for r in outcomes]] for key, label, _ in an.SIGNALS]
    by_outcome.append(
        ["Median versions posted so far", *[dec(r["median_versions"]) for r in outcomes]]
    )
    by_outcome.append(
        [
            "Median months moved, where the primary completion date moved later",
            *[dec(r["median_slip_months"]) for r in outcomes],
        ]
    )
    cif_headers = ["Signal at the landmark", "Compared among", "Trials with", "Trials without",
                   "Outside the comparison or not known", f"CIF at {long_} months with",
                   f"CIF at {long_} months without", "Ratio"]  # fmt: skip
    cif_body = [
        [r["signal"], r["among"], num(r["with"]), num(r["without"]), num(r["outside"]),
         pct(r["cif_with"]), pct(r["cif_without"]), dec(r["ratio"], 2)]
        for r in res.amendments_cif
    ]  # fmt: skip
    lines = [
        f"## 4. Amendments by the {at}-month landmark",
        "",
        _modeling_tag(res),
        f"{num(res.amendment_rows)} trials still open {at} months after registration (landmark "
        f"index {at // res.spacing_months}). Each signal compares the record as it stood at the "
        "landmark, from versions posted on or before it, with the trial's first version. "
        "Nothing posted after the landmark is read. The enrollment count is a target while its "
        "type is ESTIMATED and the number enrolled once it is ACTUAL, so the three enrollment "
        "signals are compared among trials of one type.",
        "",
        _table(
            "signals_outcome",
            f"Share of trials showing each signal at the {at}-month landmark, by what was "
            f"observed afterwards (before {res.before.isoformat()}). Each share is taken among "
            "the trials where the signal is defined and its inputs are known.",
        ),
        "",
        *markdown_table(
            ["Signal at the landmark", *[f"{r['group']} ({num(r['trials'])})" for r in outcomes]],
            by_outcome,
        ),
        "",
        f"- {pct(stopped['primary_completion_later'])} of the trials that later stopped early "
        "had moved their primary completion date later by the landmark, and "
        f"{pct(completed['primary_completion_later'])} of the trials that later completed "
        f"{cite(tables='signals_outcome')}.",
        f"- {pct(stopped['not_yet_recruiting'])} of the trials that later stopped early were "
        f"still not yet recruiting, against {pct(completed['not_yet_recruiting'])} of those "
        f"that later completed; {pct(stopped['ever_suspended'])} against "
        f"{pct(completed['ever_suspended'])} had been suspended "
        f"{cite(tables='signals_outcome')}.",
        "",
        *_figure("signals"),
        "",
        _table(
            "signals_cif",
            f"Early-stop CIF in the {long_} months after the {at}-month landmark, with and "
            f"without each signal, among the trials it is compared among. Over all "
            f"{num(res.amendment_rows)} trials it is {pct(res.amendment_overall)}.",
        ),
        "",
        *markdown_table(cif_headers, cif_body),
        "",
    ]
    signal = {r["key"]: r for r in res.amendments_cif}
    for key, text in (
        ("ever_suspended", "with a suspension on record"),
        ("not_yet_recruiting", "for trials still not yet recruiting"),
        ("primary_completion_later", "where the primary completion date moved later"),
        ("target_cut", "where the enrollment target was cut by 10% or more"),
        ("enrollment_closed", "where the enrollment count is ACTUAL"),
        ("enrollment_short", "where the number enrolled is 10% or more below the first target"),
    ):
        if key in signal:
            lines.append(
                f"- The {long_}-month CIF is {pct(signal[key]['cif_with'])} {text} and "
                f"{pct(signal[key]['cif_without'])} for the other "
                f"{signal[key]['among'].removeprefix('all ')} "
                f"{cite('signals', 'signals_cif')}."
            )
    return lines


def _registration_lag(res: Results) -> list[str]:
    cl = f"cif_{res.long}m"
    years = res.registration_years
    modeling = [r for r in years if not r["descriptive"]]
    first, last = modeling[0], modeling[-1]
    timing = {r["group"]: r for r in res.timing}
    headers = ["Registration year", "Use", "Trials", "Start date given to the day",
               "Registered after the start month", "Median days late, among those",
               "More than 1 year late", "Median days from submission to first posting"]  # fmt: skip
    body = [
        [r["year"], _use(r), num(r["trials"]), pct(r["share_day_precision"]),
         pct(r["share_after_start"]), dec(r["median_days_late"]),
         pct(r["share_over_a_year_late"]), dec(r["median_days_submit_to_post"])]
        for r in years
    ]  # fmt: skip
    timing_headers = ["Registration timing", "Trials", "Early stops observed",
                      *[f"CIF at {m} months" for m in TABLE_MONTHS],
                      f"Withdrawn within {res.long} months",
                      f"Terminated within {res.long} months"]  # fmt: skip
    timing_body = [
        [r["group"], num(r["trials"]), num(r["early_stops"]),
         *[pct(r[f"cif_{m}m"]) for m in TABLE_MONTHS], pct(r["withdrawn"]), pct(r["terminated"])]
        for r in res.timing
    ]  # fmt: skip
    on_time, within, over = (timing[k] for k in an.TIMING_ORDER[:3])
    return [
        "## 5. Registration lag",
        "",
        f"*Years before {res.before.year} are modeling-relevant and come from the cohort as of "
        f"{res.before.isoformat()}; rows from {res.before.year} on are {DESCRIPTIVE}, marked, "
        "and come from the final cohort.* Trials open at registration (landmark index 0). A "
        "trial is registered after its start month when the calendar month of its first "
        "version's start date ended before the first-post date. The comparison is by month for "
        "every trial, whatever the precision of its start date.",
        "",
        *_figure("timing"),
        "",
        _table(
            "timing_year",
            f"Registration timing by year of registration. The last year runs to "
            f"{res.cutoff.isoformat()}. The shares are taken among trials with a start date in "
            "their first version, and the days late are counted from the end of the start "
            "month.",
        ),
        "",
        *markdown_table(headers, body),
        "",
        f"- {pct(first['share_after_start'])} of the trials registered in {first['year']} were "
        f"registered after their start month, with a median delay of "
        f"{dec(first['median_days_late'])} days; in {last['year']} it was "
        f"{pct(last['share_after_start'])} and {dec(last['median_days_late'])} days "
        f"{cite('timing', 'timing_year')}.",
        f"- The first version gives the start date to the day for "
        f"{pct(first['share_day_precision'])} of the trials registered in {first['year']} and "
        f"for {pct(last['share_day_precision'])} of those registered in {last['year']} "
        f"{cite(tables='timing_year')}.",
        "",
        _table(
            "timing_cif",
            "Early-stop CIF by registration timing, and its two parts at "
            f"{res.long} months. {_modeling_tag(res).strip('*')}",
        ),
        "",
        *markdown_table(timing_headers, timing_body),
        "",
        f"- The {res.long}-month CIF is {pct(on_time[cl])} for trials registered in or before "
        f"their start month, {pct(within[cl])} for trials registered up to 1 year after it and "
        f"{pct(over[cl])} for trials registered more than 1 year after it "
        f"{cite(tables='timing_cif')}.",
        f"- Within {res.long} months {pct(on_time['withdrawn'])} of the trials registered in or "
        f"before their start month are withdrawn and {pct(on_time['terminated'])} terminated; "
        f"for trials registered more than 1 year after it, {pct(over['withdrawn'])} and "
        f"{pct(over['terminated'])} {cite(tables='timing_cif')}.",
    ]


def _post_dates(res: Results) -> list[str]:
    rows = res.post_dates
    headers = ["Year of posting", "Use", "Versions", "ESTIMATED post date",
               "Median days from submission to posting", "90th percentile"]  # fmt: skip
    body = [
        [r["year"], _use(r), num(r["versions"]), pct(r["share_estimated"]),
         dec(r["median_days_to_post"]), dec(r["p90_days_to_post"])]
        for r in rows
    ]  # fmt: skip
    lag_body = [
        [r["date_type"], "First version" if r["is_first"] else "Later version",
         num(r["versions"]), dec(r["median_days"]), dec(r["p90_days"])]
        for r in res.posting_lag
    ]  # fmt: skip
    lines = [
        "## 6. Estimated post dates",
        "",
        f"*A property of the registry's records, not of outcomes. Rows from {res.before.year} "
        f"on are still marked {DESCRIPTIVE} and count the versions of the final cohort's "
        f"trials; earlier rows, and the second table, read only versions posted before "
        f"{res.before.isoformat()}, of the trials in the cohort as of that date.* The version "
        "clock is each version's post date "
        "(Section 6). A post date marked ESTIMATED was derived by the registry and not "
        "recorded.",
        "",
        *_figure("post_dates"),
        "",
        _table(
            "post_dates",
            "Versions of cohort trials by year of posting: the share with an ESTIMATED post "
            "date, and the days from submission to posting.",
        ),
        "",
        *markdown_table(headers, body),
        "",
    ]
    modeling = [r for r in rows if not r["descriptive"]]
    full = [r for r in modeling if r["share_estimated"] == 1.0]
    partial = [r for r in modeling if r["share_estimated"] < 1.0]
    if full:
        after = "".join(f", and {pct(r['share_estimated'])} in {r['year']}" for r in partial)
        lines.append(
            f"- The ESTIMATED share is {pct(full[-1]['share_estimated'])} in every year from "
            f"{full[0]['year']} to {full[-1]['year']}{after} {cite('post_dates', 'post_dates')}."
        )
    lines += [
        "",
        _table(
            "posting_lag",
            f"Days from submission to posting for versions of cohort trials posted before "
            f"{res.before.isoformat()}, by the type of the post date. First versions set time "
            "zero and every landmark, so they are shown apart.",
        ),
        "",
        *markdown_table(
            ["Post date", "Version", "Versions", "Median days", "90th percentile"], lag_body
        ),
        "",
    ]
    for r in res.posting_lag:
        if r["date_type"] == "ACTUAL":
            which = "first versions" if r["is_first"] else "later versions"
            lines.append(
                f"- For the {num(r['versions'])} {which} with an actual post date, posting "
                f"follows submission by a median of {days(r['median_days'])}, and by "
                f"{days(r['p90_days'])} at the 90th percentile {cite(tables='posting_lag')}."
            )
    return lines


def _covid(res: Results) -> list[str]:
    peak_name, peak_rate, _ = res.covid_peak()
    baseline, shock = res.covid_summary[0], res.covid_summary[1]
    headers = ["Period", "Months", "Trials under follow-up (average)",
               *[f"{label} per 1,000" for _, label in an.COVID_SERIES]]  # fmt: skip
    body = [
        [r["period"], r["months"], num(r["open_trials"]),
         *[dec(r[f"{key}_per_1000"], 2) for key, _ in an.COVID_SERIES]]
        for r in res.covid_summary
    ]  # fmt: skip
    return [
        "## 7. The COVID period (descriptive only)",
        "",
        f"*{DESCRIPTIVE_ONLY}, not used for modeling.* Calendar months from "
        f"{COVID_START.isoformat()[:7]} to {COVID_END.isoformat()[:7]}, which include the "
        "locked test and stress-test years. A rate is the number of events posted in a month "
        "per 1,000 cohort trials under follow-up at the start of that month. A suspension is a "
        "SUSPENDED version that follows a version with another status.",
        "",
        *_figure("covid"),
        "",
        _table(
            "covid", f"{DESCRIPTIVE_ONLY}: average monthly rates per 1,000 trials under follow-up."
        ),
        "",
        *markdown_table(headers, body),
        "",
        f"- {DESCRIPTIVE_ONLY}: new suspensions averaged {dec(baseline['suspended_per_1000'], 2)} "
        f"per 1,000 trials per month in {baseline['period']} and "
        f"{dec(shock['suspended_per_1000'], 2)} in {shock['period']} {cite(tables='covid')}; "
        f"the highest month is {peak_name} with {dec(peak_rate, 1)} {cite('covid')}.",
        f"- {DESCRIPTIVE_ONLY}: terminations averaged {dec(baseline['terminated_per_1000'], 2)} "
        f"per 1,000 in {baseline['period']} and {dec(shock['terminated_per_1000'], 2)} in "
        f"{shock['period']}; withdrawals {dec(baseline['withdrawn_per_1000'], 2)} and "
        f"{dec(shock['withdrawn_per_1000'], 2)} {cite(tables='covid')}.",
    ]


def _findings(res: Results) -> list[str]:
    lines = ["## 8. Findings and what they imply for modeling", ""]
    for number, finding in enumerate(findings(res), start=1):
        lines += [
            f"{number}. **{finding.title}.** {finding.evidence}",
            f"   *Implication for modeling:* {finding.implication}",
        ]
    return lines


def _not_here() -> list[str]:
    return [
        "## Not in this report",
        "",
        "- **Why trials stop.** The reasons section (distribution by year, phase and sponsor "
        "class) waits for the final Step 6 labels and will be added as an addendum.",
        "- **Therapeutic areas.** No point-in-time therapeutic area exists in the version "
        "history (ADR 0007), so there is no breakdown by area.",
        "- **Models.** Nothing here fits or evaluates a model, and no locked origin was evaluated.",
    ]


def render(res: Results) -> str:
    """The whole document. Raises StaleFindingError before returning anything if a finding
    is no longer supported."""
    sections = [
        _header(res),
        _risk_after_registration(res),
        _phase(res),
        _competing(res),
        _amendments(res),
        _registration_lag(res),
        _post_dates(res),
        _covid(res),
        _findings(res),
        _not_here(),
    ]
    return "\n\n".join("\n".join(section) for section in sections) + "\n"
